# fly.toml app configuration file generated for propdate-media-upload on 2023-10-07T16:47:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "propdate-media-upload"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
