# fly.toml app configuration file generated for nounish-media-api on 2023-10-09T14:47:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nounish-media-api"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
